### ISSUE TITLE
Unable to convert PDF file:

### ISSUE THREAD

**Issue by mndl** [in-rolls/parse_searchable_rolls#1]
I am parsing a PDF file and the parser is unable to convert the PDF File

**CMD:**
./pdfparser.sh -f ../../AndhraPradesh/S01A085P002.PDF -s andhra

**ERROR:**

Log started at: 09/07/2018 02:39:58 PM
--------------------------------------
Processing ../../AndhraPradesh/S01A085P002.PDF...
ERROR: Unable to convert PDF file: ../../AndhraPradesh/S01A085P002.PDF
Exited.

**Comment by soodoku** [comment]
First, please don't post actual PDFs here. This has data of actual people. 

Second, check the Harvard Dataverse with the processed data. 

Third, this is a pdf without the text layer. The script we provide here is for electoral rolls with a text layer. Look into using tesseract, etc.

**Comment by isiri123** [comment]
Hi, 

I am also tried using one of the files and it seems it's without text layer (as in pdf from images). Do you know is there any file which has proper text format? 

Also, do you suggest that we first run these pdf files through tesseract and then use it for the analysis?

**Comment by soodoku** [comment]
Can't help you w/o context. 

Scripts behind the data posted here: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/MUEGDT

Please go through the readme file of the repo. carefully.

**Comment by Ganesh-S-Rai** [comment]
Hi Gaurav,
Have you tried parsing PDF files that are in Hindi ? 
I was working on the same. Would be great if you can provide some help.

**Comment by soodoku** [comment]
Yup, coming soon! Done two diff. ways!

**Comment by Ganesh-S-Rai** [comment]
I was also trying to do it. Can you provide some guidance?
or basic layout of how I should go about it?
